### ISSUE TITLE
Getting error using Logstash 1.5 Beta1

### ISSUE THREAD

**Issue by MarxDimitri** [logstash-plugins/logstash-input-meetup#2]
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Meetup meetupkey=>"551f79233a251a351215671b7a60", groupid=>"10439292,12083422,12091362,11415642,11415862,13854882,9316402,13410542,6766032,16240452,14103402,17194832,11150702,17345522,14725882,18213698,11913952", type=>"meetup", eventstatus=>"upcoming,past">
  Error: uninitialized constant LogStash::Inputs::Meetup::JSON {:level=>:error}

**Comment by ph** [comment]
This plugin is using the `json` parser from the standard library, It should use the logstash's json parser instead so the plugin can leverage rjackson's speed.

**Comment by purbon** [comment]
@ph and add test, because as this plugin even no simple test we did not discover this simple regression problem. @suyograo

**Comment by igorbarinov** [comment]
Hi! How to solve this bug?
@purbon

**Comment by purbon** [comment]
For now the easies way for you to solve this error is to add `::` in front of this https://github.com/logstash-plugins/logstash-input-meetup/blob/master/lib/logstash/inputs/meetup.rb#L67, that is the line causing the error. However the best way to fix it would be to use https://github.com/elastic/logstash/blob/master/lib/logstash/json.rb#L12 as is a faster ans better way to handle json.

@igorbarinov, are you up to make a PR to fix this? it would be much appreciate it! :+1:

**Comment by mbadran** [comment]
+1
