### ISSUE TITLE
Update plugin for 5.x plugin ecosystem

### ISSUE THREAD

**Issue by tylerjl** [logstash-plugins/logstash-input-meetup#9]
- Version: Latest
- Operating System: Ubuntu
- Sample Data: [Logs here](https://gist.github.com/tylerjl/64c238675d14237e2c4b7230e01c4b5d)
- Steps to Reproduce:
  - From within a new 5.3.0 install: `./logstash-5.3.0/bin/logstash-plugin install logstash-input-meetup`

This is probably an easy fix somewhere in the Gemfile that other plugins have undergone for the 5.x family of Logstash, I'm just not privy to what those might be  🎱

**Comment by jordansissel** [comment]
I will look and help out :)

**Comment by jordansissel** [comment]
Just as a note, you're welcome to keep using the older version of Logstash with this plugin.

I have a PR that may fix this, but I have no experience with Meetup.com and there are no tests for this plugin, so it is hard for me to evaluate the correctness of my patch alone.
